"""Project-wide mappings and label normalization constants."""

TYPE_MAPPING = {'Boat': 'Boating',
 'Boatomg': 'Boating',
 'Invalid': 'Unknown',
 'Provoked': 'Provoked',
 'Questionable': 'Unknown',
 'Sea Disaster': 'Sea Disaster',
 'Unconfirmed': 'Unknown',
 'Under investigation': 'Unknown',
 'Unprovoked': 'Unprovoked',
 'Unverified': 'Unknown',
 'Watercraft': 'Boating'}

HEMISPHERE_MAPPING = {' PHILIPPINES': 1,
 ' TONGA': 0,
 'ADMIRALTY ISLANDS': 0,
 'AFRICA': 0,
 'ALGERIA': 1,
 'AMERICAN SAMOA': 0,
 'ANDAMAN / NICOBAR ISLANDAS': 1,
 'ANDAMAN ISLANDS': 1,
 'ANGOLA': 0,
 'ANTIGUA': 1,
 'ARGENTINA': 0,
 'ARUBA': 1,
 'ASIA?': 1,
 'ATLANTIC OCEAN': 1,
 'AUSTRALIA': 0,
 'AZORES': 1,
 'BAHAMAS': 1,
 'BAHREIN': 1,
 'BANGLADESH': 1,
 'BARBADOS': 1,
 'BAY OF BENGAL': 0,
 'BELIZE': 1,
 'BERMUDA': 1,
 'BRAZIL': 0,
 'BRITISH ISLES': 1,
 'BRITISH NEW GUINEA': 0,
 'BRITISH VIRGIN ISLANDS': 1,
 'BRITISH WEST INDIES': 1,
 'BURMA': 1,
 'Between PORTUGAL & INDIA': 1,
 'CANADA': 1,
 'CAPE VERDE': 1,
 'CARIBBEAN SEA': 1,
 'CAYMAN ISLANDS': 1,
 'CENTRAL PACIFIC': 0,
 'CEYLON': 1,
 'CEYLON (SRI LANKA)': 1,
 'CHILE': 0,
 'CHINA': 1,
 'COLOMBIA': 0,
 'COLUMBIA': 1,
 'COMOROS': 0,
 'COOK ISLANDS': 0,
 'COSTA RICA': 1,
 'CRETE': 1,
 'CROATIA': 1,
 'CUBA': 1,
 'CURACAO': 1,
 'CYPRUS': 1,
 'Coast of AFRICA': 0,
 'DIEGO GARCIA': 0,
 'DJIBOUTI': 1,
 'DOMINICAN REPUBLIC': 1,
 'ECUADOR': 0,
 'EGYPT': 1,
 'EGYPT ': 1,
 'EGYPT / ISRAEL': 1,
 'EL SALVADOR': 1,
 'ENGLAND': 1,
 'EQUATORIAL GUINEA / CAMEROON': 1,
 'FALKLAND ISLANDS': 0,
 'FEDERATED STATES OF MICRONESIA': 1,
 'FIJI': 0,
 'FRANCE': 1,
 'FRENCH POLYNESIA': 0,
 'Fiji': 0,
 'GABON': 0,
 'GEORGIA': 1,
 'GHANA': 1,
 'GRAND CAYMAN': 1,
 'GREECE': 1,
 'GREENLAND': 1,
 'GRENADA': 1,
 'GUAM': 1,
 'GUATEMALA': 1,
 'GUINEA': 1,
 'GULF OF ADEN': 1,
 'GUYANA': 0,
 'HAITI': 1,
 'HONDURAS': 1,
 'HONG KONG': 1,
 'ICELAND': 1,
 'INDIA': 1,
 'INDIAN OCEAN': 0,
 'INDIAN OCEAN?': 0,
 'INDONESIA': 0,
 'IRAN': 1,
 'IRAN / IRAQ': 1,
 'IRAQ': 1,
 'IRELAND': 1,
 'ISRAEL': 1,
 'ITALY': 1,
 'ITALY / CROATIA': 1,
 'JAMAICA': 1,
 'JAPAN': 1,
 'JAVA': 0,
 'JOHNSTON ISLAND': 1,
 'KENYA': 0,
 'KIRIBATI': 1,
 'KOREA': 1,
 'KUWAIT': 1,
 'LEBANON': 1,
 'LIBERIA': 1,
 'LIBYA': 1,
 'MADAGASCAR': 0,
 'MALAYSIA': 1,
 'MALDIVE ISLANDS': 1,
 'MALDIVES': 0,
 'MALTA': 1,
 'MARSHALL ISLANDS': 1,
 'MARTINIQUE': 1,
 'MAURITIUS': 0,
 'MAYOTTE': 0,
 'MEDITERRANEAN SEA': 1,
 'MEDITERRANEAN SEA?': 1,
 'MEXICO': 1,
 'MEXICO ': 1,
 'MICRONESIA': 1,
 'MID ATLANTIC OCEAN': 1,
 'MID-PACIFC OCEAN': 1,
 'MONACO': 1,
 'MONTENEGRO': 1,
 'MOZAMBIQUE': 0,
 'NAMIBIA': 0,
 'NETHERLANDS ANTILLES': 1,
 'NEVIS': 0,
 'NEW BRITAIN': 0,
 'NEW CALEDONIA': 0,
 'NEW GUINEA': 0,
 'NEW ZEALAND': 0,
 'NICARAGUA': 1,
 'NICARAGUA ': 1,
 'NIGERIA': 1,
 'NORTH ATLANTIC OCEAN': 1,
 'NORTH ATLANTIC OCEAN ': 1,
 'NORTH PACIFIC OCEAN': 1,
 'NORTH SEA': 1,
 'NORTHERN ARABIAN SEA': 1,
 'NORTHERN MARIANA ISLANDS': 1,
 'NORWAY': 1,
 'OCEAN': 0,
 'OKINAWA': 1,
 'PACIFIC OCEAN': 1,
 'PACIFIC OCEAN ': 1,
 'PALAU': 1,
 'PALESTINIAN TERRITORIES': 1,
 'PANAMA': 1,
 'PAPUA NEW GUINEA': 0,
 'PARAGUAY': 0,
 'PERSIAN GULF': 1,
 'PERU': 0,
 'PHILIPPINES': 1,
 'PORTUGAL': 1,
 'PUERTO RICO': 1,
 'RED SEA': 1,
 'RED SEA / INDIAN OCEAN': 1,
 'RED SEA?': 1,
 'REUNION': 0,
 'REUNION ISLAND': 0,
 'ROATAN': 1,
 'RUSSIA': 1,
 'SAMOA': 0,
 'SAN DOMINGO': 0,
 'SAUDI ARABIA': 1,
 'SCOTLAND': 1,
 'SENEGAL': 1,
 'SEYCHELLES': 0,
 'SIERRA LEONE': 1,
 'SINGAPORE': 1,
 'SLOVENIA': 1,
 'SOLOMON ISLANDS': 0,
 'SOLOMON ISLANDS / VANUATU': 0,
 'SOMALIA': 1,
 'SOUTH AFRICA': 0,
 'SOUTH ATLANTIC OCEAN': 0,
 'SOUTH CHINA SEA': 1,
 'SOUTH KOREA': 1,
 'SOUTH PACIFIC OCEAN': 0,
 'SOUTHWEST PACIFIC OCEAN': 0,
 'SPAIN': 1,
 'SRI LANKA': 1,
 'ST HELENA, British overseas territory': 0,
 'ST. MAARTIN': 1,
 'ST. MARTIN': 0,
 'SUDAN': 1,
 'SUDAN?': 1,
 'SWEDEN': 1,
 'SYRIA': 1,
 'Seychelles': 0,
 'Sierra Leone': 1,
 'St Helena': 0,
 'TAIWAN': 1,
 'TANZANIA': 0,
 'TASMAN SEA': 0,
 'THAILAND': 1,
 'THE BALKANS': 1,
 'TOBAGO': 1,
 'TONGA': 0,
 'TRINIDAD & TOBAGO': 1,
 'TUNISIA': 1,
 'TURKEY': 1,
 'TURKS & CAICOS': 1,
 'TUVALU': 0,
 'UNITED ARAB EMIRATES': 1,
 'UNITED ARAB EMIRATES (UAE)': 1,
 'UNITED KINGDOM': 1,
 'URUGUAY': 0,
 'USA': 1,
 'VANUATU': 0,
 'VENEZUELA': 1,
 'VIETNAM': 1,
 'WEST INDIES': 1,
 'WESTERN SAMOA': 0,
 'YEMEN': 1,
 'YEMEN ': 1}

OCEAN_MAPPING = {'AFGHANISTAN': 'No Ocean',
 'AMERICAN SAMOA': 'Pacific',
 'ANGOLA': 'Atlantic',
 'ANTARCTICA': 'Southern',
 'ANTIGUA': 'Atlantic',
 'ARGENTINA': 'Atlantic',
 'AUSTRALIA': 'Pacific',
 'AUSTRIA': 'No Ocean',
 'AZORES': 'Atlantic',
 'BARBADOS': 'Atlantic',
 'BERMUDA': 'Atlantic',
 'BRAZIL': 'Atlantic',
 'CAPE VERDE': 'Atlantic',
 'CENTRAL PACIFIC': 'Pacific',
 'CHILE': 'Pacific',
 'COLOMBIA': 'Atlantic',
 'COMOROS': 'Indian',
 'COOK ISLANDS': 'Pacific',
 'COSTA RICA': 'No Ocean',
 'CROATIA': 'No Ocean',
 'CUBA': 'Atlantic',
 'CYPRUS': 'No Ocean',
 'CZECH REPUBLIC': 'No Ocean',
 'DIEGO GARCIA': 'Indian',
 'DJIBOUTI': 'No Ocean',
 'DOMINICAN REPUBLIC': 'Atlantic',
 'ECUADOR': 'Pacific',
 'EL SALVADOR': 'No Ocean',
 'FALKLAND ISLANDS': 'Southern',
 'FIJI': 'Pacific',
 'FRANCE': 'Atlantic',
 'FRENCH POLYNESIA': 'Pacific',
 'GABON': 'Atlantic',
 'GERMANY': 'No Ocean',
 'GHANA': 'Atlantic',
 'GREENLAND': 'Arctic',
 'HUNGARY': 'No Ocean',
 'ICELAND': 'Atlantic',
 'INDIA': 'Indian',
 'INDIAN OCEAN': 'Indian',
 'INDIAN OCEAN?': 'Indian',
 'INDONESIA': 'Pacific',
 'IRAN': 'No Ocean',
 'IRAQ': 'No Ocean',
 'JAPAN': 'Pacific',
 'KENYA': 'Indian',
 'LIBERIA': 'Atlantic',
 'MADAGASCAR': 'Indian',
 'MALAYSIA': 'Pacific',
 'MALDIVES': 'Indian',
 'MARTINIQUE': 'Atlantic',
 'MAYOTTE': 'Indian',
 'MEXICO': 'No Ocean',
 'MID ATLANTIC OCEAN': 'Atlantic',
 'NAMIBIA': 'Atlantic',
 'NEPAL': 'No Ocean',
 'NEW CALEDONIA': 'Pacific',
 'NEW ZEALAND': 'Pacific',
 'NORWAY': 'Arctic',
 'PALESTINIAN TERRITORIES': 'No Ocean',
 'PAPUA NEW GUINEA': 'Pacific',
 'PARAGUAY': 'No Ocean',
 'PHILIPPINES': 'Pacific',
 'REUNION': 'Indian',
 'REUNION ISLAND': 'Indian',
 'RUSSIA': 'Arctic',
 'SAMOA': 'Pacific',
 'SAN DOMINGO': 'Atlantic',
 'SENEGAL': 'Atlantic',
 'SEYCHELLES': 'Indian',
 'SIERRA LEONE': 'Atlantic',
 'SOLOMON ISLANDS': 'Pacific',
 'SOLOMON ISLANDS / VANUATU': 'Pacific',
 'SOUTH AFRICA': 'Indian',
 'SOUTH GEORGIA': 'Southern',
 'SOUTH PACIFIC OCEAN': 'Pacific',
 'SOUTH SANDWICH ISLANDS': 'Southern',
 'ST HELENA, British overseas territory': 'Atlantic',
 'ST. MAARTIN': 'Atlantic',
 'ST. MARTIN': 'Atlantic',
 'SWITZERLAND': 'No Ocean',
 'TANZANIA': 'Indian',
 'TONGA': 'Pacific',
 'TRINIDAD & TOBAGO': 'Atlantic',
 'TUVALU': 'Pacific',
 'URUGUAY': 'Atlantic',
 'USA': 'No Ocean',
 'VENEZUELA': 'Atlantic'}

SEX_MAPPING = {
    "F": "Female",
    "M ": "Male",
    "M": "Male",
    "N": "Unknown",
    "lli": "Unknown",
    ".": "Unknown",
}

FATAL_MAPPING = {' N': 'N',
 '2017': 'UNKNOWN',
 'F': 'UNKNOWN',
 'M': 'UNKNOWN',
 'N': 'N',
 'N ': 'N',
 'UNKNOWN': 'UNKNOWN',
 'Y': 'Y',
 'y': 'Y'}

REEF_SHARKS = [
    "Galapagos Shark",
    "Raggedtooth Shark",
    "Zambezi Shark",
    "Caribbean Reef Shark",
]
